# Generated by Django 4.2.2 on 2023-07-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netmiko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmiko.configuration')),
            ],
        ),
    ]
